version: '3'
services:
  front_app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:pass@db:3306
    ports:
      - '3000:3000'
    volumes: 
      - .:/front_app
